version: '3'
services:
  course-app:
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile.dev
    ports:
      - 3030:80
      - 3001:443
    command: nodemon server.js
    networks:
      - local
    links:
      - db
    volumes:
      - .:/app
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - local
    volumes:
      - ../data-volumes:/data/db
networks:
  local:

